### ISSUE TITLE
Add `executeDisabled()` method to RobotLifecycle

### ISSUE THREAD

**Issue by andrewda** [sertain/sertain#24]

**Comment by SUPERCILEX** [comment]
I didn't do that cuz I don't see the point... what would you want to run while disabled?

**Comment by andrewda** [comment]
We will this year when we're waiting for the FMS to send us the switch/scale colors. It will be sent at least 20ms before the start of the match, but we have to check in disabled to make sure we catch it when it first appears.

**Comment by SUPERCILEX** [comment]
Oh yeah, good point.
