### ISSUE TITLE
Add subsystem class

### ISSUE THREAD

**Issue by andrewda** [sertain/sertain#28]
We should at least allow for something like:

```kotlin
fun defaultCommand = ArcadeDrive().start()
```

instead of WPILib's

```kotlin
override fun initDefaultCommand() {
    ArcadeDrive().start()
}
```

**Comment by SUPERCILEX** [comment]
@andrewda That's actually my mistake. WPILib already has the `setDefaultCommand(...)` method which is what we should be using anyway.

**Comment by andrewda** [comment]
How about automatically extending `RobotLifecycle` from the subsystem class so we don't have to do it with every new subsystem?

**Comment by SUPERCILEX** [comment]
Oh, good idea!
