### ISSUE TITLE
Don't deploy docs if only changes are generation time changes

### ISSUE THREAD

**Issue by andrewda** [sertain/sertain#32]
Commits like https://github.com/sertain/javadocs/commit/d12c12bf2d44bde14e19d5cda32a9a4e4fb9936f are totally useless and just clutter up the commit history (even if it is all automated, it'd still be nice to only push to the documentation repo when the documentation actually needs to be changed).

Maybe check if there's the same number of files changes, additions and deletions, i.e. 1 addition and deletion per file? Or maybe there's a way to not create the generation timestamps in Dokka?

**Comment by SUPERCILEX** [comment]
Oh lol, yeah, that's pretty sad. In the Firebase world, docs are only
deployed on tag builds. I'll let you do the shell magic...

**Comment by andrewda** [comment]
That's a good idea.
