### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by JacksonCoder** [sertain/sertain#4]
As we add more features and capabilities to our library, it's important that we also document the code, in case other people want to use it. I think that ReadTheDocs could be a good place to host documentation. (for free)

**Comment by andrewda** [comment]
We should make a docs repo to host the documentation. ReadTheDocs isn't my fav.

**Comment by JacksonCoder** [comment]
Good idea.

**Comment by andrewda** [comment]
See: https://github.com/sertain/docs

**Comment by SUPERCILEX** [comment]
See @andrewda's comment. Also, we're mostly going to do docs in code and the README so nah.
