### ISSUE TITLE
Pathfinder timesteps are off

### ISSUE THREAD

**Issue by andrewda** [sertain/sertain#48]
This definitely accounts for some of the weird things we've been seeing, specifically Pathfinder not adhering to our max velocties.

https://github.com/sertain/sertain/blob/e8e1db36c077bee8ecf34dba3617175a9b41451e/core/src/main/kotlin/org/sertain/util/Pathfinder.kt#L41

I think someone might very well have been high while writing that line 😜. The comment is right but the value is wrong. Should be `0.02` = 20 millis.

**Comment by andrewda** [comment]
Using 0.02s, our PowerUp code MAX_VELOCITY should be 1.5 m/s, much more reasonable than 0.6 m/s which we were constantly going faster than. Not quite sure how acceleration will scale, but I think it should come out to something like 0.25 m/s.

**Comment by SUPERCILEX** [comment]
@andrewda 🤦‍♂️ Damn, well I guess that means I should lessen up my daily tequila shots. 😆

**Comment by andrewda** [comment]
Imma fix this one, will need some basic re-tuning before Girl's Gen.
